USE judjen;

INSERT INTO users VALUES ('3cv4', 'a@gmail.com', NULL, NULL, '0cc175b9c0f1b6a831c399e269772661', 'Mascherato 151', '2024-01-14');
INSERT INTO users VALUES ('35v4', 'b@gmail.com', "Ho una vita di merda ma la roba cringe la rende migliore", NULL, '0cc175b9c0f1b6a831c399e269772661', 'Enigma 101', '2024-01-04');
INSERT INTO users VALUES ('3434', 'c@gmail.com', NULL, NULL, '0cc175b9c0f1b6a831c399e269772661', 'Fantasma 101', '2024-02-06');
INSERT INTO users VALUES ('3bv4', 'd@gmail.com', "Non so che cazzo scrivere", NULL, '0cc175b9c0f1b6a831c399e269772661', 'Ombra 108', '2023-12-14');
INSERT INTO users VALUES ('326v', 'e@gmail.com', NULL, NULL, '0cc175b9c0f1b6a831c399e269772661', 'Spettro 143', '2024-01-21');
INSERT INTO users VALUES ('3c45', 'f@gmail.com', NULL, NULL, '0cc175b9c0f1b6a831c399e269772661', 'Cifrato 146', '2024-01-06');


INSERT INTO stories (title, content, created_on, user_id)
VALUES ('Il TELEFONO duro', "Era inverno, la nostra scuola aveva una politica estremamente dura contro i telefoni cellulari portati dagli studenti. Qualcuno aveva avvisato una delle nostre insegnanti che qualche alunno aveva portato un telefono nella nostra classe. Quindi, c'è stato un controllo improvviso di tutti gli studenti della nostra classe. Il casinista della classe fu il primo a essere controllato e, per fortuna, in quel momento stava avendo un'erezione (Una delle prime probabilmente). L'insegnante iniziò quindi a controllargli le tasche della giacca con le mani, non trovando nulla passò alle tasche dei pantaloni, sentì subito qualcosa di duro e rigido 'lì sotto'. L'insegnante che era estremamente sospettosa comincio ad urlare frasi del tipo CHE COS'È QUESTO?. In risposta, la faccia del ragazzo divenne tutta rossa e con estremo imbarazzo rimase in silenzio. A quel punto l'insegnante si rese conto di cosa fosse effettivamente e divenne anche lei rossa per l'imbarazzo. Immediatamente se ne andò senza pronunciare una sola parola.", '2024-01-15', '3cv4');
INSERT INTO stories (title, content, created_on, user_id)
VALUES ('Il bro profilattato', "Un ragazzo supplicava di non utilizzare preservativi. Letteralmente nudo, a mani e ginocchia nude, implorava di non farlo. Non ne avevamo. Ho suggerito di andare al distributore per prenderne. Ha rifiutato e ha iniziato a cercare di mettersi dei sacchi di plastica sul pene. Esatto, hai capito bene. Conosci quei dischetti per il trucco che le ragazze usano? Quelli che vengono in piccole bustine di plastica lunghe, circa delle dimensioni di un pene grande? Sì, hai indovinato. Ha svuotato i dischetti per il trucco sul pavimento e ha messo il sacchetto sul suo pene, supplicandomi di provarlo, assicurando che sarebbe stato sicuro. Ah, voleva anche che gli tirassi un peto in faccia. Ciaoooo", '2024-01-05', '35v4');
INSERT INTO stories (title, content, created_on, user_id)
VALUES ('BASTA TINDER raga diocane', "Ci siamo conosciuti su un sito di incontri online e abbiamo chattato per un po'. Lui era un analista informatico che progettava software per ospedali, mentre io sono un medico che utilizza quel software, quindi avevamo molte cose di cui parlare. Sembravamo avere valori e credenze religiose simili. I suoi messaggi erano gentili, ben scritti e premurosi. Entrambi eravamo divorziati, ancora in fase di ripresa, ma pronti a dare una nuova possibilità alla vita e all'amore. A quel punto, avevo già esperienza con gli incontri online e il mio processo di selezione era piuttosto rigoroso. Sembrava essere la persona giusta. Quando ha suggerito di incontrarci in un ristorante di tapas alla moda nelle vicinanze, ho iniziato a sentire un leggero brivido di anticipazione. Chissà? Tuttavia, tutto è improvvisamente cambiato pochi momenti dopo aver fatto l'ordine. I dettagli che aveva omesso dal suo profilo online erano scioccanti: sua moglie aveva chiesto il divorzio quando aveva annunciato il suo piano di trasferirla insieme ai LORO SETTE figli (con età compresa tra i 15 anni e gli 8 mesi) in Arabia Saudita, dove, senza conoscere l'arabo, intendeva iniziare una nuova vita come missionario. Viveva ancora con l'ex moglie, poiché non poteva permettersi gli alimenti per i figli e una casa tutta sua. Tuttavia, è stato veloce nel sottolineare che le sue 'circostanze' avrebbero offerto a me certe opportunità uniche e allettanti. Uccidere due piccioni con una fava! Come chirurgo traumatologo, avrei potuto supportarlo e i suoi sogni, e in cambio, lui avrebbe potuto realizzare il mio destino naturale di donna, ovvero essere moglie e madre. Con lui. E i suoi sette figli. E forse anche la sua ex moglie. In Arabia Saudita. Il conto, per favore!", '2024-02-07', '3434');
INSERT INTO stories (title, content, created_on, user_id)
VALUES ('Mi stavano circoincidendo senza che lo sapessi', "Quando avevo 8 anni, mia madre mi portò in questa clinica per vedere un medico e non sapevo cosa sarebbe successo fino a quando le infermiere mi portarono dentro e mi prepararono per il dottore. Quando mi fecero sdraiare, misero delle cose su braccia e gambe in modo che non potessi muovermi. All'inizio pensai che fosse davvero divertente, poi il medico entrò e cominciò ad esaminare la parte intima e un'altra infermiera le portò un vassoio con attrezzi medici, alcuni dei quali sembravano davvero appuntiti e iniziai a preoccuparmi. Mi chiese se sapevo perché mia madre mi aveva portato lì quella mattina. Non lo sapevo. Mi disse che, su richiesta di mia madre, avrebbero fatto la circoncisione tra poco. Conoscevo amici che erano stati circoncisi e sapevo cosa significava, ed ero tipo 'accidenti'. Mi diedero qualcosa per tranquillizzarmi. Ma stare sdraiato senza potermi muovere e sapere cosa stava facendo era davvero agghiacciante. Fa rabbrividire chiunque.", '2024-01-15', '3bv4');
INSERT INTO stories (title, content, created_on, user_id)
VALUES ('La zoccola della maestra', "Era il presagio di cose a venire... Avevo 5 anni e stavo avendo difficoltà con alcuni problemi di matematica che la mia insegnante delle elementari aveva mandato a casa, credo che ce ne fossero 6. Mio papà era uno scienziato, conosceva la matematica, poteva aiutarmi. È qui che ho scoperto che non mi piaceva la matematica. Ha cercato di mostrarmi come farli, ma non riuscivo a capire quello che stava cercando di dire. Mi ha urlato che non stavo prestando attenzione, mi ha trascinato fuori dalla sedia per il braccio, tenendomi così in alto che i miei piedi non toccavano il pavimento, mi ha picchiato così forte da rompere la matita che avevo in mano e che avevo messo dietro di me per proteggere il sedere. Quella è stata l'ultima volta che gli ho chiesto aiuto, e la prima di tante punizioni che si sono trasformate in percosse per 'non prestare attenzione' fino a diventare semplicemente stupida.Ha avviato la mia discesa nella scarsa autostima e nell'ansia sociale.", '2024-01-01', '326v');
INSERT INTO stories (title, content, created_on, user_id)
VALUES ('Un pò di nostalgia', "Il mio miglior ricordo d'infanzia è quando ero un ragazzino negli anni '90 e mi trovavo al parco giochi con delle bambine nere, proprio come lo sono io. Eravamo bambini, ricordo quando giocavamo insieme, è un ricordo sfocato che spesso si fa avanti e poi svanisce. Desideravo che crescessimo insieme, che avessimo avuto l'opportunità di avere bambini insieme. Non ho trascurato un amore sincero e il primo amore a prima vista. Se potessi tornare a quel giorno, lo farei. Penso giorno e notte desiderando di poter tornare a quel momento, ma sto pianificando di scriverlo nel mio libro perché è un vero ricordo della mia infanzia che continuerà a restare con me fino alla fine della mia vita. Erano le mie compagne d'infanzia, volevo crescere con loro, avere un futuro insieme, che diventassero tutte mia moglie. Eravamo tutte insieme al parco giochi, eravamo giovani. Sarei stato un buon padre e un bravo marito.", '2024-01-22', '3c45');
INSERT INTO stories (title, content, created_on, user_id)
VALUES ('Un mio amico venne rapito a 6 anni', "Giocando nel bosco a 6 anni con il mio vicino. Stavamo giocando agli esploratori. Abbiamo trovato un forte sotterraneo con dei tunnel. Ci siamo infilati in un tunnel quando il mio amico ha urlato. Mi sono girato e l'ho visto trascinato per una mano da un adulto all'indietro in un altro tunnel di collegamento. Ha smesso improvvisamente di urlare. Sono passato attraverso il tunnel e sono corso a casa. Il mio amico non era a scuola il lunedì né in nessun altro giorno. Chiunque lo abbia afferrato deve averlo rapito. La polizia ha cercato nel bosco per una settimana ma non è riuscita a trovarlo. Non ho mai raccontato a nessuno della mano che lo afferrava alla caviglia. Avevamo molti soldati che tornavano a casa dal Vietnam giù nel bosco. Solo un soldato avrebbe potuto costruire un forte così complesso. Spero che il mio amico abbia sofferto, per aver fatto soffrire i suoi genitori. Era stata sua l'idea di andare a esplorare. I poveri veterani avevano già abbastanza difficoltà ad adattarsi alla vita di ritorno a casa senza che io li mettessi in guai." , '2024-01-14', '3c45');
INSERT INTO stories (title, content, created_on, user_id)
VALUES ('Stavamo per morire', "Una volta, quando ero piccolo (5 o 6 anni), mio padre ha provato a navigare su una piccola imbarcazione su un lago aperto. Il tempo non gli era favorevole e man mano che i venti aumentavano e cambiavano rapidamente, la nostra imbarcazione ha cominciato a sbandare. A bordo c'erano mia madre (che non sapeva nuotare), mio fratello maggiore, mio fratello più piccolo, io e mio padre al timone. Il cielo si è fatto brutto e minaccioso mentre aspettavamo il soccorso. Le onde e le correnti non aiutavano i soccorritori. Stranamente, mio fratello più piccolo ed io stavamo in piedi sulla chiglia, molto al sicuro. Mio fratello maggiore stava cercando di raggiungere il timone. Mia madre si aggrappava alla vita, pensando che avrebbe perso la sua famiglia quel giorno. Mio padre cercava di raggiungere i soccorritori. Il tempo è passato, siamo tutti finiti sani e salvi a terra, e solo mia sorella (che non c'era quel giorno) avrebbe navigato con mio padre in vacanza. Questo può essere considerato come uno dei momenti più imbarazzanti?", '2024-01-14', '3bv4');
INSERT INTO stories (title, content, created_on, user_id)
VALUES ('La figura di merda più grande', "Ho perso la pazienza in un centro commerciale affollato e ho iniziato a urlare a squarciagola al mio ragazzo che stava rompendo con me. Ho continuato a gridare, citando frasi di film che sentivo si adattassero alla situazione. Ho iniziato a dondolarmi avanti e indietro come se stessi schivando pugni. Non ho idea di cosa sia scattato dentro di me e, al momento, la gente pensava che fossi sotto l'effetto di qualcosa. Ero più imbarazzata dal dire che non lo ero. Anni dopo, amici che erano presenti ancora lo tiravano fuori. Ci sono voluti anni per tornare in quel centro commerciale e tutto ciò che posso fare ora è accettare di aver agito come una completa stupida, e se la gente ne parla, la gente ne parla. È la vita. Grazie per l'opportunità di sfogarmi LOL.", '2024-01-14', '3434');
INSERT INTO stories (title, content, created_on, user_id)
VALUES ('Ho bagnato il letto della mia tipa', "Bagnare il letto nella casa dei genitori della mia ragazza. Avevo 16 anni e ero stato invitato alla casa al mare dei genitori della mia ragazza, insieme alla sua famiglia che includeva un fratello di 13 anni e una sorella di 19 anni. La prima notte ho bagnato il letto e non c'era modo di nasconderlo. Siamo rimasti lì per un lungo weekend di 4 giorni e alla fine ho bagnato il letto due volte.", '2024-01-14', '3bv4');
INSERT INTO stories (title, content, created_on, user_id)
VALUES ('Mio zio è un coglione', "Avevo 14 anni e ero seduto alla rinfusa funebre di mio padre. Uno dei suoi fratelli, mio zio, si avvicinò e notò che indossavo una catenina d'oro che mio padre portava da anni. Mi chiese se poteva averla così poteva venderla e farsi sostituire i denti, perché era tossicodipendente. Questo è successo forse un'ora dopo il funerale di mio padre. Un altro zio si avvicinò e gli disse di lasciarmi stare e di andarsene, non riusciva a credere che avesse appena fatto una cosa del genere, ecc. Io stavo già andando avanti a fatica e non avrei mai ceduto la catenina, ma essere chiesto quel giorno e per quella ragione è stato vile.", '2024-02-07', '3434');
INSERT INTO stories (title, content, created_on, user_id)
VALUES ('Da piccola ero una troia AHAHAH', "Da giovane ragazza, ero naturalmente una fan di Disney e di tutte le principesse. Beh, ero particolarmente una fan di Biancaneve e Aurora: l'intera idea di essere svegliata con un bacio mi affascinava, e volevo proprio quello. Quindi, nell'area giochi durante la ricreazione, mi avvicinavo a un paio di ragazzi e chiedevo loro se volevano giocare a 'principe e principessa', dove io mi sdraiavo per terra e, per poter tornare nel gioco, dovevano baciarmi (AHH). Gli insegnanti si accorsero di tutto, senza preoccuparsi nemmeno dei baci che cercavo di ottenere dai ragazzi, ma del fatto che io mi sdraiavo nel bel mezzo del cortile come un'idiota. Tagliai subito fuori quella storia, spaventata all'idea di finire in direzione e che i miei genitori lo scoprissero. Ma i miei baci non si fermarono lì. Non so perché ero così ossessionata, ma in ogni occasione che avevo, se c'era un ragazzo che trovavo attraente, volevo solo baciarlo. Quindi, per i primi 7/8 anni della mia vita, rendevo ragazzi 'miei fidanzati', tenevo la loro mano al parco giochi e cercavo di ottenere baci da loro", '2024-01-15', '3bv4');

INSERT INTO tags (tag_id, name) VALUES (1, 'Avventura');
INSERT INTO tags (tag_id, name) VALUES (2, 'Famiglia');
INSERT INTO tags (tag_id, name) VALUES (3, 'Fantasy');
INSERT INTO tags (tag_id, name) VALUES (4, 'Divertente');
INSERT INTO tags (tag_id, name) VALUES (5, 'Mistero');
INSERT INTO tags (tag_id, name) VALUES (6, 'Crimine');
INSERT INTO tags (tag_id, name) VALUES (7, 'Black Humor');
INSERT INTO tags (tag_id, name) VALUES (8, 'Sesso');
INSERT INTO tags (tag_id, name) VALUES (9, 'Strano');
INSERT INTO tags (tag_id, name) VALUES (10, 'Assurdo');
INSERT INTO tags (tag_id, name) VALUES (11, 'Triste');


INSERT INTO storytags (story_id, tag_id) VALUES (1, 1), (1, 3), (1, 9);
INSERT INTO storytags (story_id, tag_id) VALUES (2, 1), (2, 4), (2, 7);
INSERT INTO storytags (story_id, tag_id) VALUES (3, 3), (3, 6), (3, 10);
INSERT INTO storytags (story_id, tag_id) VALUES (4, 4), (4, 9);
INSERT INTO storytags (story_id, tag_id) VALUES (5, 5), (5, 10);
INSERT INTO storytags (story_id, tag_id) VALUES (6, 4), (6, 9), (6, 10);
INSERT INTO storytags (story_id, tag_id) VALUES (7, 4), (7, 7), (7, 9);
INSERT INTO storytags (story_id, tag_id) VALUES (8, 6), (8, 7), (8, 9);
INSERT INTO storytags (story_id, tag_id) VALUES (9, 1), (9, 3);
INSERT INTO storytags (story_id, tag_id) VALUES (10, 4), (10, 6);
INSERT INTO storytags (story_id, tag_id) VALUES (11, 4), (11, 7);
INSERT INTO storytags (story_id, tag_id) VALUES (12, 3), (12, 11);