
datasources:
  - name: local
    user: root
    password: ""
    host: localhost
    port: 3306
    db: judjen
  - name: production
    user: "judjen"
    password: "aJudjenOnPythonAnywhere23!"
    host: "judjen.mysql.pythonanywhere-services.com"
    port: 3306
    db: "judjen$default"

variables:
  - name: local
    BASE_URL: http://localhost:8000
    BASE_FE_URL: http://localhost:3000
  - name: production
    BASE_URL: https://judjen.pythonanywhere.com
    BASE_FE_URL: https://judjen.pages.dev


emails:
  - name: welcome
    title: "Welcome to JudJen"
  - name: recover_password
    title: "Recover your password"



