
datasources:
  - name: local
    user: root
    password: "11025"
    host: localhost
    port: 3306
    db: judjen

variables:
  - name: local
    BASE_URL: http://localhost:8000
    BASE_FE_URL: http://localhost:3000
  - name: production
    BASE_URL: https://videomail.pythonanywhere.com
    BASE_FE_URL: https://videomailfe.pages.dev


